#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export HISTFILE="$HOME/.zhistory"
export HISTSIZE=10000000
export SAVEHIST=10000000

export PURE_PROMPT_SYMBOL='%(!.#.$)'
export LC_ALL='gl_ES.UTF_8'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias please='sudo $(fc -nl -1)'
alias vim=`if [ -x "$(command -v nvim)" ]; then echo nvim; else echo vim; fi`
alias showip='echo $(curl -s ifconfig.me)'
alias nvm-init='source /usr/share/nvm/init-nvm.sh'
alias update='yay -Syu --noconfirm'
alias pipu="pip list --outdated --format=freeze | grep -v '^\\-e' | cut -d = -f 1 | xargs -n1 pip install -U"
alias stripexif='-makernotes:all= -composite:all= '
alias gc='git commit --no-verify'
alias gcd='git branch | fzf | xargs git checkout'
grb() {
  git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
}
alias loadenv='set -o allexport; source .env; set +o allexport'

alias ll='exa -al --git --git-ignore'
alias la='exa -al --git'
alias lat='exa -al --git --git-ignore -T'
alias lat1='exa -al --git --git-ignore -T --level=1'
alias lat2='exa -al --git --git-ignore -T --level=2'
alias lat3='exa -al --git --git-ignore -T --level=3'

# Environment
export EDITOR=nvim
export GIT_EDITOR=nvim
export XDG_CONFIG_HOME=$HOME/.config
export NPM_TOKEN=$(head -n1 ~/.npmrc | sed -n 's/\/\/npm.pkg.github.com\/:_authToken=//p')

## Go
export PATH="$HOME/go/bin:$PATH"
export GOPATH=$HOME/go
export GO111MODULE=on

# fzf
export FZF_DEFAULT_COMMAND="rg -l --files"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


export PATH="$HOME/.local/bin:$HOME/.yarn/bin:$PATH"
export PATH="$PATH:/home/leo/Documents/software/google-cloud-sdk/bin"


export CLOUDSDK_PYTHON=/usr/bin/python3.10

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/leo/code/software/google-cloud-sdk/path.zsh.inc' ]; then . '/home/leo/code/software/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/leo/code/software/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/leo/code/software/google-cloud-sdk/completion.zsh.inc'; fi

source /home/leo/code/software/zsh-notify/notify.plugin.zsh

# fuck these overly slow hooks
export HUSKY_SKIP_HOOKS=1
# source /usr/share/nvm/init-nvm.sh


export PATH="$HOME/.poetry/bin:$PATH"
