#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export PURE_PROMPT_SYMBOL='%(!.#.$)'
export LC_ALL='en_US.UTF_8'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Completions
source <(hcloud completion zsh)

# Aliases
alias please='sudo $(fc -nl -1)'
alias vim=`if [ -x "$(command -v nvim)" ]; then echo nvim; else echo vim; fi`
alias showip='echo $(curl -s ifconfig.me)'
alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'
alias update='yay -Syu --noconfirm'
alias pipu="pip list --outdated --format=freeze | grep -v '^\\-e' | cut -d = -f 1 | xargs -n1 pip install -U"
alias stripexif='-makernotes:all= -composite:all= '
source /home/leo/Documents/software/zsh-notify/notify.plugin.zsh

# Environment
export EDITOR=nvim
export GIT_EDITOR=nvim
export XDG_CONFIG_HOME=$HOME/.config

## Go
export PATH="$HOME/go/bin:$PATH"
export GOPATH=$HOME/go
export GO111MODULE=on

# fzf
export FZF_DEFAULT_COMMAND="rg -l --files"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


export PATH="$HOME/.local/bin:$HOME/.yarn/bin:$PATH"
export PATH="$PATH:/home/leo/Documents/software/google-cloud-sdk/bin"

